// Generated by gencpp from file autopilot_bridge/ParamSetListRequest.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_PARAMSETLISTREQUEST_H
#define AUTOPILOT_BRIDGE_MESSAGE_PARAMSETLISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <autopilot_bridge/ParamPair.h>

namespace autopilot_bridge
{
template <class ContainerAllocator>
struct ParamSetListRequest_
{
  typedef ParamSetListRequest_<ContainerAllocator> Type;

  ParamSetListRequest_()
    : param()  {
    }
  ParamSetListRequest_(const ContainerAllocator& _alloc)
    : param(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::autopilot_bridge::ParamPair_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::autopilot_bridge::ParamPair_<ContainerAllocator> >> _param_type;
  _param_type param;





  typedef boost::shared_ptr< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ParamSetListRequest_

typedef ::autopilot_bridge::ParamSetListRequest_<std::allocator<void> > ParamSetListRequest;

typedef boost::shared_ptr< ::autopilot_bridge::ParamSetListRequest > ParamSetListRequestPtr;
typedef boost::shared_ptr< ::autopilot_bridge::ParamSetListRequest const> ParamSetListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator1> & lhs, const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.param == rhs.param;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator1> & lhs, const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autopilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ad4bd52a388b0c97e78555e2513d443";
  }

  static const char* value(const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ad4bd52a388b0c9ULL;
  static const uint64_t static_value2 = 0x7e78555e2513d443ULL;
};

template<class ContainerAllocator>
struct DataType< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autopilot_bridge/ParamSetListRequest";
  }

  static const char* value(const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ParamPair[] param\n"
"\n"
"================================================================================\n"
"MSG: autopilot_bridge/ParamPair\n"
"string name\n"
"float64 value\n"
;
  }

  static const char* value(const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParamSetListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autopilot_bridge::ParamSetListRequest_<ContainerAllocator>& v)
  {
    s << indent << "param[]" << std::endl;
    for (size_t i = 0; i < v.param.size(); ++i)
    {
      s << indent << "  param[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::autopilot_bridge::ParamPair_<ContainerAllocator> >::stream(s, indent + "    ", v.param[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_PARAMSETLISTREQUEST_H
