// Generated by gencpp from file autopilot_bridge/Rallypoint.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_RALLYPOINT_H
#define AUTOPILOT_BRIDGE_MESSAGE_RALLYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autopilot_bridge
{
template <class ContainerAllocator>
struct Rallypoint_
{
  typedef Rallypoint_<ContainerAllocator> Type;

  Rallypoint_()
    : lat(0.0)
    , lon(0.0)
    , alt(0.0)
    , break_alt(0.0)
    , land_dir(0.0)
    , flags(0)  {
    }
  Rallypoint_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , lon(0.0)
    , alt(0.0)
    , break_alt(0.0)
    , land_dir(0.0)
    , flags(0)  {
  (void)_alloc;
    }



   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _alt_type;
  _alt_type alt;

   typedef double _break_alt_type;
  _break_alt_type break_alt;

   typedef double _land_dir_type;
  _land_dir_type land_dir;

   typedef uint8_t _flags_type;
  _flags_type flags;





  typedef boost::shared_ptr< ::autopilot_bridge::Rallypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autopilot_bridge::Rallypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Rallypoint_

typedef ::autopilot_bridge::Rallypoint_<std::allocator<void> > Rallypoint;

typedef boost::shared_ptr< ::autopilot_bridge::Rallypoint > RallypointPtr;
typedef boost::shared_ptr< ::autopilot_bridge::Rallypoint const> RallypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autopilot_bridge::Rallypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autopilot_bridge::Rallypoint_<ContainerAllocator1> & lhs, const ::autopilot_bridge::Rallypoint_<ContainerAllocator2> & rhs)
{
  return lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.alt == rhs.alt &&
    lhs.break_alt == rhs.break_alt &&
    lhs.land_dir == rhs.land_dir &&
    lhs.flags == rhs.flags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autopilot_bridge::Rallypoint_<ContainerAllocator1> & lhs, const ::autopilot_bridge::Rallypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autopilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::Rallypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::Rallypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::Rallypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18ae3a5294644e7830f081afbc682a08";
  }

  static const char* value(const ::autopilot_bridge::Rallypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18ae3a5294644e78ULL;
  static const uint64_t static_value2 = 0x30f081afbc682a08ULL;
};

template<class ContainerAllocator>
struct DataType< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autopilot_bridge/Rallypoint";
  }

  static const char* value(const ::autopilot_bridge::Rallypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lat\n"
"float64 lon\n"
"float64 alt\n"
"float64 break_alt\n"
"float64 land_dir\n"
"uint8 flags\n"
;
  }

  static const char* value(const ::autopilot_bridge::Rallypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.alt);
      stream.next(m.break_alt);
      stream.next(m.land_dir);
      stream.next(m.flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rallypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autopilot_bridge::Rallypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autopilot_bridge::Rallypoint_<ContainerAllocator>& v)
  {
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "alt: ";
    Printer<double>::stream(s, indent + "  ", v.alt);
    s << indent << "break_alt: ";
    Printer<double>::stream(s, indent + "  ", v.break_alt);
    s << indent << "land_dir: ";
    Printer<double>::stream(s, indent + "  ", v.land_dir);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_RALLYPOINT_H
