// Generated by gencpp from file autopilot_bridge/ReqPrevNMsgsRequest.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSREQUEST_H
#define AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autopilot_bridge
{
template <class ContainerAllocator>
struct ReqPrevNMsgsRequest_
{
  typedef ReqPrevNMsgsRequest_<ContainerAllocator> Type;

  ReqPrevNMsgsRequest_()
    : n(0)
    , since_seq(0)  {
    }
  ReqPrevNMsgsRequest_(const ContainerAllocator& _alloc)
    : n(0)
    , since_seq(0)  {
  (void)_alloc;
    }



   typedef uint8_t _n_type;
  _n_type n;

   typedef uint32_t _since_seq_type;
  _since_seq_type since_seq;





  typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReqPrevNMsgsRequest_

typedef ::autopilot_bridge::ReqPrevNMsgsRequest_<std::allocator<void> > ReqPrevNMsgsRequest;

typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsRequest > ReqPrevNMsgsRequestPtr;
typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsRequest const> ReqPrevNMsgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator1> & lhs, const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.n == rhs.n &&
    lhs.since_seq == rhs.since_seq;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator1> & lhs, const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autopilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4242952d50b7bebbc5d66d81eb08899";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4242952d50b7bebULL;
  static const uint64_t static_value2 = 0xbc5d66d81eb08899ULL;
};

template<class ContainerAllocator>
struct DataType< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autopilot_bridge/ReqPrevNMsgsRequest";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 n\n"
"uint32 since_seq\n"
;
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.n);
      stream.next(m.since_seq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReqPrevNMsgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autopilot_bridge::ReqPrevNMsgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "n: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.n);
    s << indent << "since_seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.since_seq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSREQUEST_H
